import path from 'node:path';
import { expect, test } from '@playwright/test';

/**
 * Roadmap item: **Uploads**.
 *
 * Two shapes, and the second is the one that matters in practice. `setInputFiles` accepts a path on
 * disk, which means committing binary fixtures and keeping them in sync with the tests - or it accepts
 * an in-memory `{ name, mimeType, buffer }`, which lets a test generate exactly the file it needs
 * (including a deliberately malformed one) with nothing to check in.
 *
 * Note also that no click is involved: Playwright sets the input's files directly rather than driving
 * the OS file picker, which is why this works headless and in CI at all.
 */
// `__dirname`, not `path.dirname(fileURLToPath(import.meta.url))`. Playwright transpiles spec files to
// CommonJS unless something forces ESM - and `import.meta` is exactly such a forcing construct, after
// which the transpiled `require` calls in the same file fail with "require is not defined in ES module
// scope". Confirmed by hitting that error here, not assumed.
const currentDir = __dirname;

test.describe('Uploads', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/uploads.html');
  });

  test('a file is uploaded from an in-memory buffer, with no fixture on disk', async ({ page }) => {
    const csv = 'id,name\n1,generated by the test\n';

    await page.getByTestId('single-file').setInputFiles({
      name: 'in-memory.csv',
      mimeType: 'text/csv',
      buffer: Buffer.from(csv)
    });

    await expect(page.getByTestId('single-file-result')).toHaveText(
      `in-memory.csv (${Buffer.byteLength(csv)} bytes, text/csv)`
    );
    // Read back through the page, so this asserts the bytes actually crossed over - not just the name.
    await expect(page.getByTestId('file-contents')).toHaveText(csv.trim());
  });

  test('a file is uploaded from a path on disk', async ({ page }) => {
    // This spec file itself: a file that is guaranteed to exist, so nothing extra has to be committed
    // just to have something to upload.
    const filePath = path.join(currentDir, 'uploads.spec.ts');

    await page.getByTestId('single-file').setInputFiles(filePath);

    await expect(page.getByTestId('single-file-result')).toContainText('uploads.spec.ts');
  });

  test('several files go to a multiple input at once', async ({ page }) => {
    await page.getByTestId('multiple-files').setInputFiles([
      { name: 'first.txt', mimeType: 'text/plain', buffer: Buffer.from('one') },
      { name: 'second.txt', mimeType: 'text/plain', buffer: Buffer.from('two') }
    ]);

    await expect(page.getByTestId('multiple-files-result')).toHaveText('2 files: first.txt, second.txt');
  });

  test('passing an empty array clears the selection', async ({ page }) => {
    const input = page.getByTestId('single-file');

    await input.setInputFiles({ name: 'temp.txt', mimeType: 'text/plain', buffer: Buffer.from('x') });
    await expect(page.getByTestId('single-file-result')).toContainText('temp.txt');

    await input.setInputFiles([]);
    await expect(page.getByTestId('single-file-result')).toHaveText('no file selected');
  });
});
